services:
    postgres:
        image: postgres:18-alpine
        container_name: dakal-database
        restart: always
        environment:
            POSTGRES_USER: user_dakal
            POSTGRES_PASSWORD: mypassword
            POSTGRES_DB: db_dakal
        ports:
            - '5433:5432'
        volumes:
            - db_data:/var/lib/postgresql/data

volumes:
    db_data:
